### ISSUE TITLE
Invalid Number

### ISSUE THREAD

**Issue by kcancook** [salgieri/StorJ-Telegraf-Plugin#1]
Getting "Error in plugin [inputs.exec]:  invalid number" from telegraf when the delta is returned as "..." and storjstats converts it to "NaN" which would lead to gaps in the reporting.

I updated my storjstats.js and added this code in the fixDeltaValue function:

 if(isNaN(delta))
    {
        return 0;
    }

**Comment by salgieri** [comment]
Thanks, nice hack. Have updated.
